# Generated by Django 5.2.8 on 2025-11-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False, help_text='Tick if this is the current live stream')),
                ('video_embed_url', models.URLField(help_text='Embed URL (YouTube, Twitch, etc.)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('purchase_url', models.URLField(blank=True, help_text='External link to buy / more info')),
                ('is_active', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Space Junk', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('bandcamp_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
        ),
    ]
