# Generated by Django 5.2.8 on 2025-11-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('embed_url', models.URLField(help_text='Embed URL (YouTube, Vimeo, Twitch, etc.)')),
                ('is_active', models.BooleanField(default=False, help_text='Tick to make this the default active feed.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='livestream',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='video_embed_url',
            field=models.URLField(help_text='Embed URL to YouTube/Twitch/etc.'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='purchase_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
